config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :students
  devise_for :users
  resources :sections
  resources :courses
  resources :professors
  # Redirect to the sections page when accessing the main page
  root to:"sections#index"
  #handle users who have been redirected to login first
  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  belongs_to :professor
  #has_many :students, through: :enrollments
  has_many :enrollments, :dependent => :destroy
  validates_uniqueness_of :name, scope: :course_id

  validates :name, presence: true
  validates :room, presence: true
  validates :semester, presence: true

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  #Ensure that the users are authenticated before allowing access to the page
  before_filter :authenticate_user!
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    #@sections = Section.all
    @sections = if params[:sectionsearch]
      #Section.where('name Like ?',"%#{params[:sectionsearch]}%")
      key = "%#{params[:sectionsearch]}%"
      Section.where('name Like :search or semester Like :search or
        room Like :search', search: key)
    else
      Section.all
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name, :room, :semester, :course_id, :professor_id, :sectionsearch)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(section) do |f| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :room %>
    <%= f.number_field :room %>
  </div>

  <div class="field">
    <%= f.label :semester %>
    <%= f.text_field :semester %>
  </div>

  <div class="field">
    <%= f.label :course_id %>
    <%= f.select(:course_id,
   		options_from_collection_for_select(Course.all, :id, :name)) %>
    <%#= f.text_field :course_id %>
  </div>

  <div class="field">
    <%= f.label :professor_id %>
    <%= f.select(:professor_id,
    options_from_collection_for_select(Professor.all, :id, :name)) %>
    <%#= f.text_field :professor_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<br>
  <p align = "center"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></td>

<%= form_tag(sections_path, method: :get) do %>
  <%= text_field_tag :sectionsearch, params[:sectionsearch] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Room</th>
      <th>Semester</th>
      <th>Course</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name %></td>
        <td><%= section.room %></td>
        <td><%= section.semester %></td>
        <td><%= section.course.name %></td>
        <td><%= section.professor.name %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @section.name %>
</p>

<p>
  <strong>Room:</strong>
  <%= @section.room %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @section.semester %>
</p>

<p>
  <strong>Course:</strong>
  <%= @section.course.name %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @section.professor.name %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>