config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :students
  devise_for :users
  resources :sections
  resources :courses
  resources :professors
  # Redirect to the sections page when accessing the main page
  root to:"sections#index"
  #handle users who have been redirected to login first
  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :sections, dependent: :destroy
  #has_many :enrollments, through: :sections
  validates :name, presence: true
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  #Ensure that the users are authenticated before allowing access to the page
  before_filter :authenticate_user!
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
  #  @professors = Professor.all
    @professors = if params[:enteredsearch]
      Professor.where('name Like ?', "%#{params[:enteredsearch]}%")
    else
      Professor.all
    end
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:name, :enteredsearch)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_for(professor) do |f| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>

<br>
  <p align = "center"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></p>

<%= form_tag(professors_path, method: :get) do %>
  <%= text_field_tag :enteredsearch, params[:enteredsearch] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.name %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @professor.name %>
</p>
<table>
  <thead>
    <tr>
      <th>Course Name</th>
      <th>Room Number</th>
      <th>Semester</th>
      <th>Section Number</th>
      <th>Enrolled Student(s)</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @professor.sections.each do |section| %>
    <tr>
        <td><%= section.course.name %></td>
        <td><%= section.room %></td>
        <td><%= section.semester %></td>
        <td><%= section.name %></td>
        <td>Student Name(s)</td>
        <tr>
        <% section.enrollments.each do |enrol|%>
          <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td> <%= enrol.student.name %></td>
          </tr>
        <% end %>
      </tr>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>